function [PTCS] = PaulTor_Rainbow(N)
% Paul Tor's Rainbow Color Schemes
RBI = 1/255.*[232 236 251;
    217 204 227;
    209 187 215; 
    202 172 203;
    186 141 180;
    174 118 163;
    170 111 158;
    153 79 136;
    136 46 114;
    25 101 176;
    67 125 191;
    82 137 199;
    97 149 207;
    123 175 222;
    78 178 101;
    144 201 135;
    202 224 171;
    247 240 86;
    247 203 69;
    246 193 65;
    244 167 54;
    241 147 45;
    238 128 38;
    232 96 28;
    230 85 24;
    220 5 12;
    165 23 14;
    114 25 14;
    66 21 10];
    if N == 1
        PTCS = RBI(10,:);
    elseif N == 2
        PTCS = [RBI(10,:);
            RBI(26,:)];
    elseif N == 3
        PTCS = [RBI(10,:);
            RBI(18,:);
            RBI(26,:)];
    elseif N == 4
        PTCS = [RBI(10,:);
            RBI(15,:);
            RBI(18,:);
            RBI(26,:)];
    elseif N == 5
        PTCS = [RBI(10,:);
            RBI(14,:);
            RBI(15,:);
            RBI(18,:);
            RBI(26,:)];
    elseif N == 6
        PTCS = [RBI(10,:);
            RBI(14,:);
            RBI(15,:);
            RBI(17,:);
            RBI(18,:);
            RBI(26,:)];
    elseif N == 7
        PTCS = [RBI(9,:);
            RBI(10,:);
            RBI(14,:);
            RBI(15,:);
            RBI(17,:);
            RBI(18,:);
            RBI(26,:)];
    elseif N == 8
        PTCS = [RBI(9,:);
            RBI(10,:);
            RBI(14,:);
            RBI(15,:);
            RBI(17,:);
            RBI(18,:);
            RBI(23,:);
            RBI(26,:)];
    elseif N == 9
        PTCS = [RBI(9,:);
            RBI(10,:);
            RBI(14,:);
            RBI(15,:);
            RBI(17,:);
            RBI(18,:);
            RBI(23,:);
            RBI(26,:);
            RBI(28,:)];
    elseif N == 10
        PTCS = [RBI(9,:);
            RBI(10,:);
            RBI(14,:);
            RBI(15,:);
            RBI(17,:);
            RBI(18,:);
            RBI(21,:);
            RBI(24,:);
            RBI(26,:);
            RBI(28,:)];
    elseif N == 11
        PTCS = [RBI(9,:);
            RBI(10,:);
            RBI(12,:);
            RBI(14,:);
            RBI(15,:);
            RBI(17,:);
            RBI(18,:);
            RBI(21,:);
            RBI(24,:);
            RBI(26,:);
            RBI(28,:)];
    elseif N == 12
        PTCS = [RBI(3,:);
            RBI(6,:);
            RBI(9,:);
            RBI(10,:);
            RBI(12,:);
            RBI(14,:);
            RBI(15,:);
            RBI(17,:);
            RBI(18,:);
            RBI(21,:);
            RBI(24,:);
            RBI(26,:)];
    elseif N == 13
        PTCS = [RBI(3,:);
            RBI(6,:);
            RBI(9,:);
            RBI(10,:);
            RBI(12,:);
            RBI(14,:);
            RBI(15,:);
            RBI(16,:);
            RBI(17,:);
            RBI(18,:);
            RBI(21,:);
            RBI(24,:);
            RBI(26,:)];
    elseif N == 14
        PTCS = [RBI(3,:);
            RBI(6,:);
            RBI(9,:);
            RBI(10,:);
            RBI(12,:);
            RBI(14,:);
            RBI(15,:);
            RBI(16,:);
            RBI(17,:);
            RBI(18,:);
            RBI(20,:);
            RBI(22,:);
            RBI(24,:);
            RBI(26,:)];
    elseif N == 15
        PTCS = [RBI(3,:);
            RBI(6,:);
            RBI(9,:);
            RBI(10,:);
            RBI(12,:);
            RBI(14,:);
            RBI(15,:);
            RBI(16,:);
            RBI(17,:);
            RBI(18,:);
            RBI(20,:);
            RBI(22,:);
            RBI(24,:);
            RBI(26,:);
            RBI(28,:)];
    elseif N == 16
        PTCS = [RBI(3,:);
            RBI(5,:);
            RBI(7,:);
            RBI(9,:);
            RBI(10,:);
            RBI(12,:);
            RBI(14,:);
            RBI(15,:);
            RBI(16,:);
            RBI(17,:);
            RBI(18,:);
            RBI(20,:);
            RBI(22,:);
            RBI(24,:);
            RBI(26,:);
            RBI(28,:)];
    elseif N == 17
        PTCS = [RBI(3,:);
            RBI(5,:);
            RBI(7,:);
            RBI(8,:);
            RBI(9,:);
            RBI(10,:);
            RBI(12,:);
            RBI(14,:);
            RBI(15,:);
            RBI(16,:);
            RBI(17,:);
            RBI(18,:);
            RBI(20,:);
            RBI(22,:);
            RBI(24,:);
            RBI(26,:);
            RBI(28,:)];
    elseif N == 18
        PTCS = [RBI(3,:);
            RBI(5,:);
            RBI(7,:);
            RBI(8,:);
            RBI(9,:);
            RBI(10,:);
            RBI(12,:);
            RBI(14,:);
            RBI(15,:);
            RBI(16,:);
            RBI(17,:);
            RBI(18,:);
            RBI(20,:);
            RBI(22,:);
            RBI(24,:);
            RBI(26,:);
            RBI(27,:);
            RBI(28,:)];
    elseif N == 19
        PTCS = [RBI(2,:);
            RBI(4,:);
            RBI(5,:);
            RBI(7,:);
            RBI(8,:);
            RBI(9,:);
            RBI(10,:);
            RBI(12,:);
            RBI(14,:);
            RBI(15,:);
            RBI(16,:);
            RBI(17,:);
            RBI(18,:);
            RBI(20,:);
            RBI(22,:);
            RBI(24,:);
            RBI(26,:);
            RBI(27,:);
            RBI(28,:)];
    elseif N == 20
        PTCS = [RBI(2,:);
            RBI(4,:);
            RBI(5,:);
            RBI(7,:);
            RBI(8,:);
            RBI(9,:);
            RBI(10,:);
            RBI(11,:);
            RBI(13,:);
            RBI(14,:);
            RBI(15,:);
            RBI(16,:);
            RBI(17,:);
            RBI(18,:);
            RBI(20,:);
            RBI(22,:);
            RBI(24,:);
            RBI(26,:);
            RBI(27,:);
            RBI(28,:)];
    elseif N == 21
        PTCS = [RBI(2,:);
            RBI(4,:);
            RBI(5,:);
            RBI(7,:);
            RBI(8,:);
            RBI(9,:);
            RBI(10,:);
            RBI(11,:);
            RBI(13,:);
            RBI(14,:);
            RBI(15,:);
            RBI(16,:);
            RBI(17,:);
            RBI(18,:);
            RBI(19,:);
            RBI(21,:);
            RBI(23,:);
            RBI(25,:);
            RBI(26,:);
            RBI(27,:);
            RBI(28,:)];
    elseif N == 22
        PTCS = [RBI(2,:);
            RBI(4,:);
            RBI(5,:);
            RBI(7,:);
            RBI(8,:);
            RBI(9,:);
            RBI(10,:);
            RBI(11,:);
            RBI(13,:);
            RBI(14,:);
            RBI(15,:);
            RBI(16,:);
            RBI(17,:);
            RBI(18,:);
            RBI(19,:);
            RBI(21,:);
            RBI(23,:);
            RBI(25,:);
            RBI(26,:);
            RBI(27,:);
            RBI(28,:);
            RBI(29,:)];
    elseif N == 23
        PTCS = [RBI(1,:);
            RBI(2,:);
            RBI(4,:);
            RBI(5,:);
            RBI(7,:);
            RBI(8,:);
            RBI(9,:);
            RBI(10,:);
            RBI(11,:);
            RBI(13,:);
            RBI(14,:);
            RBI(15,:);
            RBI(16,:);
            RBI(17,:);
            RBI(18,:);
            RBI(19,:);
            RBI(21,:);
            RBI(23,:);
            RBI(25,:);
            RBI(26,:);
            RBI(27,:);
            RBI(28,:);
            RBI(29,:)];
    end
end

